### ISSUE TITLE
Automate new updates

### ISSUE THREAD

**Issue by wangwillian0** [JuliaCI/julia-snap#6]
The most recent version of Julia in the official Debian repo is 1.5.3 while the current LTS is 1.6.4. Given the fact that a lot of people will try to install Julia from the official repos first and how easy is to create a snap from the official binaries in contrast to building debs, it would be convenient to maintain a snap version and eventually drop the outdated package in Debian.

Some of previous problems:

1. Problem of getting the Julia 32 bit in a 64 bit machine - is just some small error in the snapcraft.yaml, [julia-mrcinv](https://github.com/mrcinv/julia-snap/) seems to work.
2. Snap Store bureaucracy  - There is a need for manual approval to get [multiple channels ](https://snapcraft.io/docs/channels)(eg: stable, lts) and to publish the app using [classic confinement](https://snapcraft.io/docs/reviewing-classic-confinement-snaps) (instead of the sandbox permissions), both can be a one time thing, allowing to automate the following releases.   
3.  Install multiple versions of Julia -  This isn't needed for those wanting to use snap as replacement of apt but there is already an [experimental feature for it](https://snapcraft.io/blog/parallel-installs-test-and-run-multiple-instances-of-snaps).

**Comment by PallHaraldsson** [comment]
I mentioned it here so it's tracked, the snap should maybe rather install juliaup (that installs julia release by default).

>the official Debian repo is 1.5.3

The same problem here, should install juliaup? Not sure if it's good or bad/conflicting or irrelevant if both add juliaup.

snap has confinement, apt doesn't. Or rather you need non-default option to get out of the confinement(?). For juliaup it might be ok to have, except it downloads julia for you so not sure about that actual install part.

Is the snap at least installing 64-bit? Because I couldn't test (on Mint), and 32-bit (old default) is problematic. [julia-mrcinv](https://github.com/mrcinv/julia-snap/) is at 1.7.1, now also outdated... but better and worse than LTS.

**Comment by p-zubieta** [comment]
The latest snap is installing the correct build now AFAICT.

Regarding supporting stable releases, I actually think it would make sense support them through snap directly. I'll look into this soon.

**Comment by PallHaraldsson** [comment]
Thanks,

If you have any power over the description (at the snap page), then it states "over 2400 packages", but there are now over 8200 registered packages. Can you update it, say to "over 8000". I'm not sure where to suggest it elsewhere.

**Comment by p-zubieta** [comment]
Thanks, it should be updated now.
